### ISSUE TITLE
Unable to remove openId configuration

### ISSUE THREAD

**Issue by magicsunday** [zorn-v/nextcloud-social-login#54] opened 2018-09-07 06:18 UTC
I specified an openid configuration. If I remove it (none left), save the updated configuration and reload the "social logins" settings page, the configuration is still present.

**Comment by chiyi4488** [comment] 2018-09-08 02:54
Me,too.

**Comment by chiyi4488** [comment] 2018-09-08 02:55
I can't delete both Custom OpenID Connect and Custom OAuth2.

**Comment by chiyi4488** [comment] 2018-09-08 03:05
![default](https://user-images.githubusercontent.com/30853081/45249692-0576d280-b357-11e8-81f3-60d192869890.png)

**Comment by zorn-v** [comment] 2018-09-09 10:10
Fixed in v1.10.1

**Comment by chiyi4488** [comment] 2018-09-09 11:39
Thanks!

**Comment by chiyi4488** [comment] 2018-09-10 10:48
https://user-images.githubusercontent.com/30853081/45249692-0576d280-b357-11e8-81f3-60d192869890.png


Is it normal to delete openid to display custum_oids? I updated it still... (but can delete the custom openid project)

**Comment by chiyi4488** [comment] 2018-09-11 08:07
Yes.

**Comment by zorn-v** [comment] 2018-09-11 12:08
And ? Last OIDC not deleted  in v1.10.1 ?

**Comment by chiyi4488** [comment] 2018-09-12 14:01
Yes.but it display {custom_oidc}
Is this not a bug?

**Comment by chiyi4488** [comment] 2018-09-14 08:11
Ok,I see.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Closed** 2018-09-18 10:36 UTC

**Comment by zorn-v** [comment] 2018-09-21 00:53
@chiyi4488 can you check correctness of current translation ?
https://github.com/zorn-v/nextcloud-social-login/blob/5c9cc29be046262fc51ce46e9633f6039cea36e9/l10n/zh_TW.js#L5

**Comment by chiyi4488** [comment] 2018-09-21 15:10
Yes,this translation is ok.
